### ISSUE TITLE
singleclick事件中的參數未定義

### ISSUE THREAD

**Issue by wayne2002323** [kiang/vote2020#6]
singleclick事件中的參數未定義(main.js:108)

`content.innerHTML = '';`

content推測是$('#sidebarContent')

簡易測試由console中補上後正常運作
`var content = $('#sidebarContent');`

**Comment by kiang** [comment]
我發現我貼錯連結了 XD

但程式已經修正，主要是程式碼調整風格的時候沒有把舊程式碼移除乾淨
https://github.com/kiang/vote2022/commit/fd759f04d3efd91990b378119e3d7f94966e2326
